### ISSUE TITLE
docker-compose error

### ISSUE THREAD

**Issue by madhuakula** [lalithr95/fuzzapi#31]
Hi,

When I followed the docker instructions and started the containers. The following error while browsing to the application.

Migrations are pending error

To resolve this again we have to exec into the container and resolve by running migrations command

```
docker exec -it fuzzapi_web_1 bash
```

Then run the below command to resolve.

```
bin/rake db:migrate RAILS_ENV=development
```

It will be great if we can add this migrations into the Dockerfile it self.

Thanks for cool project :+1:

**Comment by Thomasarun** [comment]
Hi,

I was also getting the same error "Migrations are pending error" earlier and after running executing the migration and rebuilding commands as given below, I was able to see the UI in http:locahost:3000.

1)Clone the repository into your local machine

2)cd /path/Fuzzapi, move to Fuzzapi directory

3)Install Docker in your local machine

4)Go to docker container and run;
 
root@kali:~/Fuzzapi# docker exec -it fuzzapi_web_1 bash
root@containerID:/app#bin/rake db:migrate RAILS_ENV=development

5)Now rebuild by commiting the changes to the docker file;

root@kali:~/Fuzzapi# docker commit fuzzapi_web_1

6)Run docker-compose build to build the image locally.

7)Run docker-compose up to run the server.

8)Open http://localhost:3000 in browser which should point to the application url

9)Sign-Up and start using the Fuzzapi.

But while initiating any API testing I was getting error as depicted below;

![fuzzapi issues](https://cloud.githubusercontent.com/assets/21146270/19444024/7051e4d0-94ac-11e6-9216-393f4b48b51f.JPG)

**Comment by lalithr95** [comment]
@Thomasarun 
Sorry that I didn't add the step, I'll add info to documentation, Above error is because app was not able to connect to redis URL, Can you confirm that redis is properly setup ?

Thanks for trying out!! 

@madhuakula

**Comment by hshar7** [comment]
Any way to fix this? @lalithr95 
My dump:
`
docker-compose up
Pulling redis (redis:latest)...
latest: Pulling from library/redis
386a066cd84a: Already exists
769149e3a45c: Pull complete
1f43b3c0854a: Pull complete
70e928127ad8: Pull complete
9ad9c0058d76: Pull complete
bc845722f255: Pull complete
105d1e8cd76a: Pull complete
Digest: sha256:c2ce5403bddabd407c0c63f67566fcab6facef90877de58f05587cdf244a28a8
Status: Downloaded newer image for redis:latest
Creating fuzzapi_redis_1
Creating fuzzapi_sidekiq_1
Creating fuzzapi_web_1
Attaching to fuzzapi_redis_1, fuzzapi_sidekiq_1, fuzzapi_web_1
redis_1    | 1:C 22 Nov 22:25:39.444 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1    |                 _._                                                  
redis_1    |            _.-``__ ''-._                                             
redis_1    |       _.-``    `.  `_.  ''-._           Redis 3.2.5 (00000000/0) 64 bit
redis_1    |   .-`` .-```.  ```\/    _.,_ ''-._                                   
redis_1    |  (    '      ,       .-`  | `,    )     Running in standalone mode
redis_1    |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
redis_1    |  |    `-._   `._    /     _.-'    |     PID: 1
redis_1    |   `-._    `-._  `-./  _.-'    _.-'                                   
redis_1    |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redis_1    |  |    `-._`-._        _.-'_.-'    |           http://redis.io        
redis_1    |   `-._    `-._`-.__.-'_.-'    _.-'                                   
redis_1    |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redis_1    |  |    `-._`-._        _.-'_.-'    |                                  
redis_1    |   `-._    `-._`-.__.-'_.-'    _.-'                                   
redis_1    |       `-._    `-.__.-'    _.-'                                       
redis_1    |           `-._        _.-'                                           
redis_1    |               `-.__.-'                                               
redis_1    | 
redis_1    | 1:M 22 Nov 22:25:39.445 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1    | 1:M 22 Nov 22:25:39.445 # Server started, Redis version 3.2.5
redis_1    | 1:M 22 Nov 22:25:39.445 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1    | 1:M 22 Nov 22:25:39.445 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1    | 1:M 22 Nov 22:25:39.445 * The server is now ready to accept connections on port 6379
sidekiq_1  | /usr/local/bundle/bundler/gems/API-fuzzer-eb4d4dcd92ac/lib/API_Fuzzer/redirect_check.rb:38: warning: nested repeat operator '?' and '*' was replaced with '*' in regular expression: /\A(\w+)=(.?*)\z/
web_1      | /usr/local/bundle/bundler/gems/API-fuzzer-eb4d4dcd92ac/lib/API_Fuzzer/redirect_check.rb:38: warning: nested repeat operator '?' and '*' was replaced with '*' in regular expression: /\A(\w+)=(.?*)\z/
sidekiq_1  | 2016-11-22T22:25:42.895Z 1 TID-gsi85jrzo INFO: Booting Sidekiq 4.2.5 with redis options {:url=>"redis://127.0.0.1:6379/0"}
web_1      | => Booting Puma
web_1      | => Rails 4.2.7.1 application starting in development on http://0.0.0.0:3000
web_1      | => Run `rails server -h` for more startup options
web_1      | => Ctrl-C to shutdown server
sidekiq_1  | 2016-11-22T22:25:43.536Z 1 TID-gsi85jrzo INFO: Running in ruby 2.2.6p396 (2016-11-15 revision 56800) [x86_64-linux]
sidekiq_1  | 2016-11-22T22:25:43.536Z 1 TID-gsi85jrzo INFO: See LICENSE and the LGPL-3.0 for licensing details.
sidekiq_1  | 2016-11-22T22:25:43.537Z 1 TID-gsi85jrzo INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
sidekiq_1  | Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
sidekiq_1  | /usr/local/bundle/gems/redis-3.3.1/lib/redis/client.rb:345:in `rescue in establish_connection'
sidekiq_1  | /usr/local/bundle/gems/redis-3.3.1/lib/redis/client.rb:331:in `establish_connection'
sidekiq_1  | /usr/local/bundle/gems/redis-3.3.1/lib/redis/client.rb:101:in `block in connect'
sidekiq_1  | /usr/local/bundle/gems/redis-3.3.1/lib/redis/client.rb:293:in `with_reconnect'
sidekiq_1  | /usr/local/bundle/gems/redis-3.3.1/lib/redis/client.rb:100:in `connect'
sidekiq_1  | /usr/local/bundle/gems/newrelic_rpm-3.17.0.325/lib/new_relic/agent/instrumentation/redis.rb:66:in `block in connect'
sidekiq_1  | /usr/local/bundle/gems/newrelic_rpm-3.17.0.325/lib/new_relic/agent/datastores.rb:111:in `wrap'
sidekiq_1  | /usr/local/bundle/gems/newrelic_rpm-3.17.0.325/lib/new_relic/agent/instrumentation/redis.rb:65:in `connect'
sidekiq_1  | /usr/local/bundle/gems/redis-3.3.1/lib/redis/client.rb:364:in `ensure_connected'
sidekiq_1  | /usr/local/bundle/gems/redis-3.3.1/lib/redis/client.rb:221:in `block in process'
sidekiq_1  | /usr/local/bundle/gems/redis-3.3.1/lib/redis/client.rb:306:in `logging'
sidekiq_1  | /usr/local/bundle/gems/redis-3.3.1/lib/redis/client.rb:220:in `process'
sidekiq_1  | /usr/local/bundle/gems/redis-3.3.1/lib/redis/client.rb:120:in `call'
sidekiq_1  | /usr/local/bundle/gems/newrelic_rpm-3.17.0.325/lib/new_relic/agent/instrumentation/redis.rb:42:in `block in call'
sidekiq_1  | /usr/local/bundle/gems/newrelic_rpm-3.17.0.325/lib/new_relic/agent/datastores.rb:111:in `wrap'
sidekiq_1  | /usr/local/bundle/gems/newrelic_rpm-3.17.0.325/lib/new_relic/agent/instrumentation/redis.rb:41:in `call'
sidekiq_1  | /usr/local/bundle/gems/redis-3.3.1/lib/redis.rb:251:in `block in info'
sidekiq_1  | /usr/local/bundle/gems/redis-3.3.1/lib/redis.rb:58:in `block in synchronize'
sidekiq_1  | /usr/local/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
sidekiq_1  | /usr/local/bundle/gems/redis-3.3.1/lib/redis.rb:58:in `synchronize'
sidekiq_1  | /usr/local/bundle/gems/redis-3.3.1/lib/redis.rb:250:in `info'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.5/lib/sidekiq.rb:112:in `block in redis_info'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.5/lib/sidekiq.rb:94:in `block in redis'
sidekiq_1  | /usr/local/bundle/gems/connection_pool-2.2.0/lib/connection_pool.rb:64:in `block (2 levels) in with'
sidekiq_1  | /usr/local/bundle/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `handle_interrupt'
sidekiq_1  | /usr/local/bundle/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `block in with'
sidekiq_1  | /usr/local/bundle/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
sidekiq_1  | /usr/local/bundle/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.5/lib/sidekiq.rb:91:in `redis'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.5/lib/sidekiq.rb:105:in `redis_info'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.5/lib/sidekiq/cli.rb:71:in `run'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.5/bin/sidekiq:12:in `<top (required)>'
sidekiq_1  | /usr/local/bundle/bin/sidekiq:17:in `load'
sidekiq_1  | /usr/local/bundle/bin/sidekiq:17:in `<top (required)>'
sidekiq_1  | /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
sidekiq_1  | /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
sidekiq_1  | /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
sidekiq_1  | /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
sidekiq_1  | /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
sidekiq_1  | /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
sidekiq_1  | /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
sidekiq_1  | /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
sidekiq_1  | /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
sidekiq_1  | /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
sidekiq_1  | /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
sidekiq_1  | /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
sidekiq_1  | /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
sidekiq_1  | /usr/local/bundle/bin/bundle:22:in `load'
sidekiq_1  | /usr/local/bundle/bin/bundle:22:in `<main>'
fuzzapi_sidekiq_1 exited with code 1
web_1      | [1] Puma starting in cluster mode...
web_1      | [1] * Version 3.6.0 (ruby 2.2.6-p396), codename: Sleepy Sunday Serenity
web_1      | [1] * Min threads: 1, max threads: 1
web_1      | [1] * Environment: development
web_1      | [1] * Process workers: 2
web_1      | [1] * Preloading application
web_1      | [1] * Listening on tcp://0.0.0.0:3000
web_1      | [1] Use Ctrl-C to stop
web_1      | Puma master process about to fork. Closing existing Active record connections.
web_1      | [1] - Worker 0 (pid: 7) booted, phase: 0
web_1      | [1] - Worker 1 (pid: 11) booted, phase: 0
`

**Comment by Os3r3um** [comment]
As a FYI, the same error is received by a non docker user which got this app running by issueing "bundle install".

**Comment by lalithr95** [comment]
Problem docker redis image is trying to connect to 127.0.0.1 which can't be accessed. I have updated code to use redis host instead. #44 

Apologies for delay in response. 
Thanks for trying tool 😃
