### ISSUE TITLE
Please add dependency list clearly. 

### ISSUE THREAD

**Issue by bugwrangler** [lalithr95/fuzzapi#33]
E.G -

devise-4.2.0 requires ruby version >= 2.1.0, which is incompatible with the current version, ruby 2.0.0p648

**Comment by lalithr95** [comment]
@bugwrangler Sorry for incorrect dependency version. Quick fix would be use ruby 2.3.0 for project. You can easily run by `rvm install ruby-2.3.0` and `rvm use 2.3.0`

I'll add ruby version to Gemfile.
Thanks for creating an issue.

**Comment by pwntoken** [comment]
*pg_config* fails.

Added SS to rectify.

![screen shot 2016-11-25 at 2 46 40 pm](https://cloud.githubusercontent.com/assets/11158935/20620112/1dfd8e92-b31e-11e6-9e71-dfae54afb960.png)

**Comment by Greenjam94** [comment]
I think I'm having the same issue however I'm not sure what needs to be set to use 2.3.1 instead of 2.0. I just installed ruby & rbenv on my mac and this is the result I get when trying to bundle install.

<img width="471" alt="screen shot 2016-12-02 at 2 32 30 pm" src="https://cloud.githubusercontent.com/assets/5766832/20847483/4798da3a-b89c-11e6-85a8-e9144aee3619.png">

**Comment by lalithr95** [comment]
I have updated ruby version to 2.3.0 and fixed docker issues in #44 This should fix the issue.

Apologies for delay in response. Thanks for trying tool
